### ISSUE TITLE
Connector cables

### ISSUE THREAD

**Issue by gerard33** [llevering/orcon-mvs-15r-esp8266#1]
First of all, thanks for sharing this.

Regarding the connector cables, I have ordered the JST PH 2.0 4P from this link -> https://nl.aliexpress.com/item/33024685895.html and they fit perfectly.
I have changed the order of the cables so the colors are more in line with the order on the MV board and use them for my solution with a Qubino dimmer.

I would like to try your solution as well because I want to read the tacho of the motor when it's controlled from the Orcon remotes, which is not possible with the Qubino solution.
As I have only little knowledge on electrical schemas, can you please share some more information on how you wired things up? Maybe add some photos of the solution as well?

Cheers,
Gerard33 (Gimme on tweakers)

**Comment by llevering** [comment]
![IMG_20201222_084148210](https://user-images.githubusercontent.com/2834866/104239498-e32b7d00-545a-11eb-958b-b8898d1d75f6.jpg)
![IMG_20201222_084125462](https://user-images.githubusercontent.com/2834866/104239513-e7f03100-545a-11eb-83f1-e0e3ce74c3dc.jpg)
![IMG_20201222_084139634](https://user-images.githubusercontent.com/2834866/104239524-ec1c4e80-545a-11eb-9f1d-2033395c042b.jpg)
![IMG_20201226_110523113](https://user-images.githubusercontent.com/2834866/104239535-f0e10280-545a-11eb-9130-22b48fa29458.jpg)

These are the best images I've got. The first three are of the breadboard prototype. The last one of the pcb I soldered in the end (hope to never having to do that again, I am not doing that to well).

You can also try to build the 'final' solution on a breadboard. Might work as well, but mine was a bit unstable with some connections not being reliable enough. And it is a bit harder to integrate in the MV box.

I know the last one isn't too helpfully schema wise, but it shows a bit the advantage of integrating it all on a (prototype) pcb.

**Comment by llevering** [comment]
And I've added your JST PH recommendation, thanks!
